env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends: 
  - airbnb-base
  - plugin:mocha/recommended
overrides:
  - files:
      - test/**/*.js
    rules:
      func-names: off
      prefer-arrow-callback: off
parserOptions:
  ecmaVersion: latest
rules: {
 'no-unused-vars': ['error', { argsIgnorePattern: 'next' }],
 "mocha/max-top-level-suites": ["warn", {limit: 2}],
 "import/no-extraneous-dependencies": ["error", {"devDependencies": true}], # Otherwise got the "supertest should be listed in project dependencies, not devDependencies"
 prefer-arrow-callback: off,
 func-names: off,
 "quotes": "off"
}
