name: Fake deploy branch

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  fake_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
        
      - name: Print out "Now deploying branch..."
      - uses: nelonoel/branch-name@v1.0.1
      - run: "echo Now deploying branch: ${BRANCH_NAME} to the test server"
