name: Test reports

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  NODE_ENV: development

jobs:
  create_test_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create mocha test report
        run: npm run test-report

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: test-results.json
